# Generated by Django 4.1.7 on 2023-05-27 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_resourceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('pin', models.CharField(max_length=6)),
                ('father_name', models.CharField(max_length=255)),
                ('cnic', models.CharField(max_length=13)),
                ('fk_training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.training')),
            ],
        ),
    ]
