# Generated by Django 4.1.7 on 2023-06-04 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_training_attachements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='attachements',
        ),
        migrations.RemoveField(
            model_name='training',
            name='resources',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
